name: Github - first
on: [push]
jobs:	
    Github-actions:
       runs-on: ubuntu-latest
       steps:
         - name: python
           run: 
             python3 --version
         - name: docker
           run:
             docker --version 
         - name: pylint
           run:
             pylint app.py
         - name: docker
           run:
             docker build --tag test-flask-app .
