name: Github-first
on: [push]
jobs:	
    Step_1:
       runs-on: ubuntu-latest
       steps:
         - name: python version
           run: 
             python3 --version
         - name: docker version
           run:
             docker --version 
    Step_2:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v2
         - name: Install pylint
           run:
             pylint app.py
    Step_3:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v2
         - name: build a image
           run:
             sudo docker build -t test-flask-app .
